#SERVER
spring.application.name=springboot_leaf
server.port=8083

# DB
spring.datasource.url=jdbc:log4jdbc:mysql://localhost:3306/chatting_platform?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&&serverTimezone=UTC
spring.datasource.driverClassName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.username=root
spring.datasource.password=1111

#thymeleaf auto refresh
spring.thymeleaf.cache=false
#thymeleaf config
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.check-template-location=true
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false

# MyBatis Config
mybatis.mapper-locations=classpath:/mybatis/**/*.xml
mybatis.type-aliases-package=com.example.demo
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=null


# \uc2dc\ud050\ub9ac\ud2f0 \uc778\uc99d \ucc98\ub9ac \uacfc\uc815\uc744 \uc0c1\uc138\ud788 \ucd9c\ub825 (DEBUG \ub808\ubca8)
logging.level.org.springframework.security.authentication=DEBUG

# \ube44\ubc00\ubc88\ud638 \uc554\ud638\ud654 \ubc0f \ube44\uad50 \ub85c\uc9c1 \ucd9c\ub825 (TRACE \ub808\ubca8)
logging.level.org.springframework.security.crypto=TRACE

# SQL \ucffc\ub9ac\uc640 \ud30c\ub77c\ubbf8\ud130\ub97c \ud655\uc778\ud558\uace0 \uc2f6\uc744 \ub54c (\uc774\ubbf8 \uc0ac\uc6a9 \uc911\uc774\uc2dc\ub77c\uba74 \uc81c\uc678)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
